import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Voidspace',
  description: 'Terms of Service for Voidspace — NEAR Protocol ecosystem intelligence platform.',
};

export default function TermsPage() {
  return (
    <article className="legal-content">
      <header className="mb-10">
        <h1 className="text-3xl sm:text-4xl font-bold text-text-primary mb-3">Terms of Service</h1>
        <p className="text-sm text-text-muted">Last updated: February 2026</p>
      </header>

      <Section title="1. Acceptance of Terms">
        <p>
          By accessing or using Voidspace (&quot;the Platform&quot;), including all features, tools, content, and services
          offered at voidspace.io, you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree,
          you must discontinue use immediately.
        </p>
      </Section>

      <Section title="2. Description of Service">
        <p>
          Voidspace is a NEAR Protocol ecosystem intelligence, education, and AI-powered development platform. Our services include:
        </p>
        <ul>
          <li>Ecosystem analytics and opportunity tracking (&quot;Voids&quot;)</li>
          <li>AI-powered smart contract builder (&quot;Sanctum&quot;)</li>
          <li>Educational content and learning paths</li>
          <li>Observatory and project analytics</li>
          <li>Visual generation tools</li>
        </ul>
      </Section>

      <Section title="3. Eligibility">
        <p>
          You must be at least <strong className="text-near-green">18 years of age</strong> to use Sanctum or any AI-powered development features.
          General informational content on the Platform may be accessed by users of all ages, but on-chain interactions and smart contract
          deployment require you to be 18 or older.
        </p>
      </Section>

      <Section title="4. No Financial Advice">
        <p>
          <strong className="text-amber-400">Nothing on Voidspace constitutes financial, investment, tax, or legal advice.</strong>{' '}
          All information — including ecosystem analytics, opportunity data, token information, and AI-generated insights —
          is provided for informational and educational purposes only. You should consult qualified professionals before making
          any financial decisions.
        </p>
      </Section>

      <Section title="5. Sanctum — AI Smart Contract Builder">
        <p>Sanctum is an AI-powered tool that assists users in generating smart contract code for the NEAR Protocol. By using Sanctum, you acknowledge and agree:</p>
        <ul>
          <li>All code generated by Sanctum is provided <strong>&quot;AS-IS&quot;</strong> without any warranty.</li>
          <li>You are <strong>solely responsible</strong> for reviewing, auditing, testing, and deploying any smart contract code.</li>
          <li>Voidspace is <strong>not responsible</strong> for any smart contracts deployed via Sanctum, including bugs, vulnerabilities, financial losses, or unintended behavior.</li>
          <li>AI-generated code may contain errors. Professional audit is strongly recommended before mainnet deployment.</li>
          <li>You assume <strong>all risk</strong> for on-chain interactions and deployed contracts.</li>
        </ul>
      </Section>

      <Section title="6. User Responsibilities &amp; Conduct">
        <p>You agree not to:</p>
        <ul>
          <li>Use the Platform to create malicious, fraudulent, or illegal smart contracts</li>
          <li>Attempt to exploit, hack, or compromise Platform infrastructure</li>
          <li>Abuse AI features (e.g., prompt injection, attempts to bypass safety guardrails)</li>
          <li>Use the Platform for money laundering, sanctions evasion, or other illegal activities</li>
          <li>Misrepresent AI-generated content as professionally audited code</li>
        </ul>
        <p>See our <a href="/legal/acceptable-use" className="text-near-green hover:underline">Acceptable Use Policy</a> for full details.</p>
      </Section>

      <Section title="7. Assumption of Risk">
        <p>
          Blockchain and smart contract technology carry inherent risks. By using Voidspace, you acknowledge:
        </p>
        <ul>
          <li>On-chain transactions are <strong>irreversible</strong>.</li>
          <li>Smart contracts may behave unexpectedly, leading to loss of funds.</li>
          <li>You assume <strong>all risk</strong> for any on-chain interactions initiated through or inspired by the Platform.</li>
          <li>Voidspace bears <strong>no liability</strong> for losses from using the Platform, its tools, or deployed code.</li>
        </ul>
      </Section>

      <Section title="8. NEAR Protocol — Third-Party Relationship">
        <p>
          Voidspace is an independent, third-party tool built for the NEAR ecosystem. We are <strong>not affiliated with,
          endorsed by, or part of the NEAR Foundation</strong> or NEAR Protocol core team. NEAR Protocol has its own terms
          of service and governance. Your use of the NEAR blockchain is subject to its own terms and risks.
        </p>
      </Section>

      <Section title="9. Intellectual Property">
        <p>
          Smart contract code generated through Sanctum is yours to use. Voidspace retains no ownership over code you generate.
          However, the Platform itself — including its design, branding, educational content, and AI models — remains the
          intellectual property of Voidspace.
        </p>
      </Section>

      <Section title="10. Subscription &amp; Payments">
        <p>
          Certain features (e.g., Sanctum Pro) may require a paid subscription processed via Stripe. By subscribing, you
          agree to Stripe&apos;s terms of service. Refund policies will be outlined at the time of purchase.
        </p>
      </Section>

      <Section title="11. Account Termination">
        <p>
          We reserve the right to <strong>suspend or terminate your access</strong> to Voidspace at our sole discretion,
          with or without notice, for any reason — including violation of these Terms, the Acceptable Use Policy,
          or any conduct we deem harmful to the Platform or its users.
        </p>
      </Section>

      <Section title="12. Disclaimer of Warranties">
        <p>
          <strong className="text-amber-400">THE PLATFORM IS PROVIDED &quot;AS-IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES
          OF ANY KIND</strong>, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. We disclaim all warranties including,
          without limitation, implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
        </p>
      </Section>

      <Section title="13. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, Voidspace and its team shall not be liable for any indirect, incidental,
          special, consequential, or punitive damages — including loss of profits, data, or digital assets — arising from
          your use of the Platform.
        </p>
      </Section>

      <Section title="14. Changes to Terms">
        <p>
          We may update these Terms at any time. Material changes will be indicated by updating the &quot;Last updated&quot; date.
          Continued use of the Platform after changes constitutes acceptance of the new Terms.
        </p>
      </Section>

      <Section title="15. Contact">
        <p>
          For questions about these Terms, email us at{' '}
          <a href="mailto:team@voidspace.io" className="text-near-green hover:underline">
            team@voidspace.io
          </a>{' '}
          or reach us on X at{' '}
          <a href="https://x.com/voidspacenear" target="_blank" rel="noopener noreferrer" className="text-near-green hover:underline">
            @VoidSpaceNear
          </a>.
        </p>
      </Section>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-xl font-semibold text-text-primary mb-3">{title}</h2>
      <div className="space-y-3 text-text-secondary text-[15px] leading-relaxed [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-1.5 [&_li]:text-text-secondary [&_strong]:text-text-primary">
        {children}
      </div>
    </section>
  );
}
