'use client';

import { useState, useRef } from 'react';
import { Upload, Flame, AlertTriangle, AlertCircle, Info, CheckCircle, Copy, Loader2 } from 'lucide-react';

interface Vulnerability {
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
  title: string;
  description: string;
  line?: number;
  suggestion: string;
}

interface RoastResult {
  overallScore: number;
  summary: string;
  vulnerabilities: Vulnerability[];
  gasIssues: string[];
  styleIssues: string[];
  positives: string[];
}

export function RoastMode() {
  const [code, setCode] = useState('');
  const [isRoasting, setIsRoasting] = useState(false);
  const [result, setResult] = useState<RoastResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    const reader = new FileReader();
    reader.onload = (e) => {
      setCode(e.target?.result as string);
    };
    reader.readAsText(file);
  };

  const handleRoast = async () => {
    if (!code.trim()) return;
    
    setIsRoasting(true);
    setError(null);
    setResult(null);
    
    try {
      const response = await fetch('/api/sanctum/roast', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code }),
      });
      
      const data = await response.json();
      
      if (data.error) {
        throw new Error(data.error);
      }
      
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to roast contract');
    } finally {
      setIsRoasting(false);
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical': return 'text-red-500 bg-red-500/10 border-red-500/30';
      case 'high': return 'text-orange-500 bg-orange-500/10 border-orange-500/30';
      case 'medium': return 'text-yellow-500 bg-yellow-500/10 border-yellow-500/30';
      case 'low': return 'text-blue-500 bg-blue-500/10 border-blue-500/30';
      default: return 'text-gray-500 bg-gray-500/10 border-gray-500/30';
    }
  };

  const getSeverityIcon = (severity: string) => {
    switch (severity) {
      case 'critical': return <AlertCircle className="w-5 h-5" />;
      case 'high': return <AlertTriangle className="w-5 h-5" />;
      case 'medium': return <AlertTriangle className="w-5 h-5" />;
      case 'low': return <Info className="w-5 h-5" />;
      default: return <Info className="w-5 h-5" />;
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-green-400';
    if (score >= 70) return 'text-yellow-400';
    if (score >= 50) return 'text-orange-400';
    return 'text-red-400';
  };

  const copyReport = () => {
    if (!result) return;
    
    const report = `
🔥 ROAST MY CONTRACT REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Security Score: ${result.overallScore}/100

${result.summary}

VULNERABILITIES FOUND: ${result.vulnerabilities.length}
${result.vulnerabilities.map(v => `
[${v.severity.toUpperCase()}] ${v.title}
${v.description}
Fix: ${v.suggestion}
`).join('')}

GAS ISSUES: ${result.gasIssues.length}
${result.gasIssues.map(g => `• ${g}`).join('\n')}

POSITIVES:
${result.positives.map(p => `✓ ${p}`).join('\n')}

Generated by Voidspace Sanctum
    `.trim();
    
    navigator.clipboard.writeText(report);
  };

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      {/* Header */}
      <div className="flex-shrink-0 p-4 border-b border-border-subtle bg-void-black/30">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-red-500/20 flex items-center justify-center">
            <Flame className="w-6 h-6 text-red-400" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-text-primary">Roast My Contract</h2>
            <p className="text-sm text-text-muted">Paste your contract and watch it get torn apart</p>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-4">
        {!result ? (
          <div className="space-y-4">
            {/* Code input */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-sm font-medium text-text-secondary">Contract Code</label>
                <div className="flex gap-2">
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept=".rs,.txt"
                    onChange={handleFileUpload}
                    className="hidden"
                  />
                  <button
                    onClick={() => fileInputRef.current?.click()}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-void-gray border border-border-subtle rounded-lg hover:border-near-green/30 transition-colors"
                  >
                    <Upload className="w-4 h-4" />
                    Upload .rs
                  </button>
                </div>
              </div>
              
              <textarea
                value={code}
                onChange={(e) => setCode(e.target.value)}
                placeholder="Paste your Rust smart contract here..."
                className="w-full h-80 px-4 py-3 rounded-xl bg-surface border border-border focus:border-near-green/50 focus:outline-none focus:ring-1 focus:ring-near-green/30 text-white font-mono text-sm resize-none"
              />
            </div>

            {/* Error message */}
            {error && (
              <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/30 text-red-400">
                {error}
              </div>
            )}

            {/* Roast button */}
            <button
              onClick={handleRoast}
              disabled={!code.trim() || isRoasting}
              className="w-full py-4 rounded-xl bg-gradient-to-r from-red-500 to-orange-500 text-white font-semibold text-lg hover:from-red-600 hover:to-orange-600 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center justify-center gap-3"
            >
              {isRoasting ? (
                <>
                  <Loader2 className="w-6 h-6 animate-spin" />
                  Roasting...
                </>
              ) : (
                <>
                  <Flame className="w-6 h-6" />
                  🔥 ROAST IT 🔥
                </>
              )}
            </button>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Score card */}
            <div className="p-6 rounded-2xl bg-gradient-to-br from-void-gray to-surface border border-border-subtle">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-text-primary">Security Score</h3>
                <div className="flex gap-2">
                  <button
                    onClick={copyReport}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-void-black/50 border border-border-subtle rounded-lg hover:border-near-green/30 transition-colors"
                  >
                    <Copy className="w-4 h-4" />
                    Copy Report
                  </button>
                  <button
                    onClick={() => setResult(null)}
                    className="px-3 py-1.5 text-sm bg-void-black/50 border border-border-subtle rounded-lg hover:border-near-green/30 transition-colors"
                  >
                    Roast Another
                  </button>
                </div>
              </div>
              
              <div className="flex items-center gap-6">
                <div className={`text-6xl font-bold ${getScoreColor(result.overallScore)}`}>
                  {result.overallScore}
                </div>
                <div className="text-2xl text-text-muted">/100</div>
                <div className="flex-1 text-text-secondary">
                  {result.summary}
                </div>
              </div>
            </div>

            {/* Vulnerabilities */}
            {result.vulnerabilities.length > 0 && (
              <div className="space-y-3">
                <h3 className="text-lg font-semibold text-text-primary flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5 text-red-400" />
                  Vulnerabilities ({result.vulnerabilities.length})
                </h3>
                
                {result.vulnerabilities.map((vuln, i) => (
                  <div
                    key={i}
                    className={`p-4 rounded-xl border ${getSeverityColor(vuln.severity)}`}
                  >
                    <div className="flex items-start gap-3">
                      {getSeverityIcon(vuln.severity)}
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-1">
                          <span className="font-semibold">{vuln.title}</span>
                          <span className="text-xs px-2 py-0.5 rounded-full bg-current/20 uppercase">
                            {vuln.severity}
                          </span>
                          {vuln.line && (
                            <span className="text-xs text-text-muted">Line {vuln.line}</span>
                          )}
                        </div>
                        <p className="text-sm opacity-80 mb-2">{vuln.description}</p>
                        <div className="text-sm">
                          <span className="font-medium">💡 Fix: </span>
                          {vuln.suggestion}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Gas issues */}
            {result.gasIssues.length > 0 && (
              <div className="space-y-3">
                <h3 className="text-lg font-semibold text-text-primary flex items-center gap-2">
                  ⛽ Gas Issues ({result.gasIssues.length})
                </h3>
                <div className="p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/30">
                  <ul className="space-y-2">
                    {result.gasIssues.map((issue, i) => (
                      <li key={i} className="flex items-start gap-2 text-yellow-400">
                        <span>•</span>
                        <span>{issue}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}

            {/* Positives */}
            {result.positives.length > 0 && (
              <div className="space-y-3">
                <h3 className="text-lg font-semibold text-text-primary flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  What You Did Right
                </h3>
                <div className="p-4 rounded-xl bg-green-500/10 border border-green-500/30">
                  <ul className="space-y-2">
                    {result.positives.map((pos, i) => (
                      <li key={i} className="flex items-start gap-2 text-green-400">
                        <CheckCircle className="w-4 h-4 mt-0.5 flex-shrink-0" />
                        <span>{pos}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
